name: Daily Sofwave Scraper

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 09:00 UTC
  workflow_dispatch:     # Manual trigger available

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies (Playwright + Google Sheets)
        run: |
          pip install playwright gspread google-auth
          playwright install chromium

      - name: Run Playwright Scraper
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          python scraper.py
