name: Daily Sofwave API Scraper

on:
  schedule:
    - cron: '0 9 * * *'  # Every day at 09:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread google-auth
          pip install gspread google-auth pycountry

      - name: Run scraper
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          python scraper.py
